"""RDP5 wrapper and output parser.

RDP5 is a Java/Windows application distributed as an executable or jar.  Its
command-line interface is driven by a project file and writes a CSV report.  The
module never imports or requires RDP5 at import time: :func:`run_rdp5` probes
for the configured executable and, if it is unavailable, logs a warning and
returns an empty breakpoint frame so the recombination stage can continue with
whatever other tools are present.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from ..config import get
from ..pipeline import StageError, get_logger, have_executable, run_command
from .partition import BREAKPOINT_COLUMNS, normalise_breakpoints

__all__ = ["run_rdp5", "parse_rdp5_output"]

logger = get_logger("recombination.rdp5")


def _empty() -> pd.DataFrame:
    return pd.DataFrame(columns=BREAKPOINT_COLUMNS)


def _resolve_executable(configured: str) -> str | None:
    """Return a usable RDP5 executable path, or ``None``."""
    if not configured:
        return None
    candidate = Path(configured)
    if candidate.exists():
        return str(candidate)
    if have_executable(configured):
        return configured
    return None


def _build_project_file(alignment: Path, project_path: Path, config) -> Path:
    """Write a minimal RDP5 project file referencing the alignment.

    RDP5's project format is version-specific; this writes the documented,
    human-readable form used by the batch interface and lets the tool populate
    the rest.  The options mirror ``recombination.rdp5`` config keys.
    """
    discontiguous = bool(get(config, "recombination.rdp5.discontiguous", False))
    domain_wise = bool(get(config, "recombination.rdp5.domain_wise", True))
    project_path.parent.mkdir(parents=True, exist_ok=True)
    project_path.write_text(
        "# RDP5 project file generated by hbvpol\n"
        f"alignment={alignment}\n"
        f"discontiguous={str(discontiguous).lower()}\n"
        f"domain_wise={str(domain_wise).lower()}\n",
        encoding="utf-8",
    )
    return project_path


def parse_rdp5_output(path: str | Path) -> pd.DataFrame:
    """Parse an RDP5 CSV report into the tidy breakpoint schema.

    RDP5 CSV reports often contain a few comment/preface lines before the real
    header; the parser scans for the first comma-separated header row and then
    delegates column normalisation to :func:`normalise_breakpoints`.
    """
    path = Path(path)
    if not path.exists():
        return _empty()

    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    header_index: int | None = None
    for index, line in enumerate(lines):
        low = line.lower()
        if "," in line and any(token in low for token in ("recombinant", "begin", "start", "sequence")):
            header_index = index
            break
        if "recombinant_id" in low and "bp_start" in low:
            header_index = index
            break
    if header_index is None:
        return _empty()

    import io

    text = "\n".join(lines[header_index:])
    try:
        frame = pd.read_csv(io.StringIO(text))
    except Exception as error:  # pragma: no cover - defensive
        logger.warning("could not parse RDP5 CSV %s: %s", path, error)
        return _empty()
    return normalise_breakpoints(frame, tool="rdp5")


def run_rdp5(alignment, config, workdir) -> pd.DataFrame:
    """Run RDP5 on ``alignment`` and return its breakpoints.

    Fails soft: a missing executable, a non-zero exit or an unparseable report
    all yield a warning and an empty (but correctly typed) DataFrame.
    """
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    # run_command sets cwd=workdir, so the alignment path must be absolute.
    alignment_path = Path(alignment).resolve()

    executable_name = str(get(config, "recombination.rdp5.executable", "rdp5") or "rdp5")
    executable = _resolve_executable(executable_name)
    if executable is None:
        logger.warning("RDP5 executable %r not found; skipping RDP5", executable_name)
        return _empty()

    project = _build_project_file(alignment_path, workdir / "rdp5_project.rdp", config)
    out_csv = workdir / "rdp5_output.csv"
    log_path = workdir / "rdp5.log"

    try:
        run_command(
            [executable, "-p", str(project), "-o", str(out_csv)],
            cwd=workdir,
            log_path=log_path,
            check=False,
        )
    except StageError as error:  # pragma: no cover - external tool behaviour
        logger.warning("RDP5 invocation failed: %s", error)
        return _empty()

    if not out_csv.exists():
        logger.warning("RDP5 produced no report at %s; skipping", out_csv)
        return _empty()
    return parse_rdp5_output(out_csv)
